### ISSUE TITLE
USER STORY : Smart Marketing

### ISSUE THREAD

**Issue by BjornBishop** [BjornBishop/Agile-project-1#5]
## User Story Template
As an **administrator**, I can **use the poll data and comment key-words** so that **to advertise and market in popular locations**

## User Acceptance Criteria 
- Polling must gather running locations.  
- Polling data should be transformed into statistics with scalability in mind.
- Comments should have key-word search for locations being mentioned.
- Comment key-words and running locations data must be stored in a separate database. 

## Tasks
- [ ] create mutable list of popular locations. Stored in external database.
- [ ] add AI bot to comments. Search keywords for street names. Save comments for qualification. 
- [ ] script to sort historic data from external database based on most votes etc.
