### ISSUE TITLE
USER STORY: Reset Password

### ISSUE THREAD

**Issue by BjornBishop** [BjornBishop/Agile-project-1#6]
## User Story Template
As a **user**, I can **Reset my password securely and automatically** so that **I have access throughout the day**

## User Acceptance Criteria 
- The password reset function requires the user to verify self.
- The reset password is encrypted and stored securely 
- The reset password function is automated 

## Tasks
- [ ] reset password requires email verification or sms verification 
- [ ] Using hashing algorithms to hash passwords
- [ ] salt password for good luck.
- [ ] install "keeper" for automated & secure password management.
